# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: instrumentisto/rsync-ssh

pipelines:
  tags:
    release-*:
      - step:
          name: rsync app
          script:
            - rsync -aP app u83047909@home602158197.1and1-data.host:flow-rss.com/htdocs/
      - step:
          name: rsync robot
          script:
            - rsync -aP robot u83047909@home602158197.1and1-data.host:flow-rss.com/htdocs/
